############################################
# Auto generated by configure tool.
# Copyright by Lovelace.Lee.
# Building time 2016-09-28-13:37:04.
############################################
SRCS := $(wildcard *.cpp)
OBJS := $(patsubst %.cpp, %.o,$(SRCS))
OBDS := $(patsubst %.cpp, %.d,$(SRCS))

.PHONY: all clean distclean
all:$(OBJS)
%.o:%.cpp
	@echo "Building file: $(notdir $<) ..."
	g++ -c -Wall -O3 -Wno-psabi   -o"$@" "$<"
	@echo "Finished building: $(notdir $@)"
clean:
	rm -rf $(OBJS) $(OBDS)
distclean:
	$(MAKE) clean
	rm -f .makefile
