############################################
# Auto generated by configure tool.
# Copyright by Lovelace.Lee.
# Building time 2017-05-03-19:25:08.
############################################
SRCS := $(wildcard *.c)
OBJS := $(patsubst %.c, %.o,$(SRCS))
OBDS := $(patsubst %.c, %.d,$(SRCS))

.PHONY: all clean distclean
all:$(OBJS)
%.o:%.c
	@echo "Building file: $(notdir $<) ..."
	arm-hisiv500-linux-gcc -c -Wall -O3 -Wno-psabi  -I"/opt/nfshost/serverdisk/github/opt/uvproject/uviodemo/./install/include"  -I"/opt/nfshost/serverdisk/github/opt/uvproject/uviodemo/install" -I"/opt/nfshost/serverdisk/github/opt/uvproject/uviodemo/install/include" -I"/opt/nfshost/serverdisk/github/opt/uvproject/uviodemo/install/lib" -I"/opt/nfshost/serverdisk/github/opt/uvproject/uviodemo/install/lib/pkgconfig" -o"$@" "$<"
	@echo "Finished building: $(notdir $@)"
clean:
	rm -rf $(OBJS) $(OBDS)
distclean:
	$(MAKE) clean
	rm -f .makefile
